version: "3.5"
services:
  backend:
    build: .
    command: sh -c "python manage.py migrate  && uwsgi --http :8000 --module parrotsite.wsgi"
    container_name: djangoapp
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devops-sample-django-app_default
    volumes:
      - app-data:/devops-sample-django-app/media/uploads

  db:
    container_name: "django_db"
    image: postgres:16-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    networks:
      - devops-sample-django-app_default
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  devops-sample-django-app_default:
volumes:
  db-data:
  app-data:

