version: "3.5"
services:
  backend:
    build: .
    command: sh -c "python manage.py migrate  && uwsgi --http :8000 --module parrotsite.wsgi"
    container_name: djangoapp
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    networks:
      - devops-sample-django-app_default
    volumes:
      - type: bind
        source: ./uploads
        target: /devops-sample-django-app/uploads

  db:
    container_name: "django_db"
    image: postgres:16-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
#      [ "CMD", "pg_isready", "-q", "-d", "worker", "-U", "postgres" ]
#      test: [ "CMD-SHELL", "pg_isready", "-U", "worker", "-d", "app", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    networks:
      - devops-sample-django-app_default
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  devops-sample-django-app_default:
volumes:
  db-data:

